/*
  f90_unix_io.c : Determine values of constants for f90_unix_io

   This file is part of Posix90

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301, USA. 

*/

#include <stdio.h>

main(){

    printf("! DO NOT EDIT THIS FILE. \n");
    printf("! It is created from f90_unix_io_const.c\n");
    printf("integer, parameter :: EOF=%d\n", EOF);
    printf("integer, parameter :: FILE_KIND=%d\n", sizeof(FILE *));
    printf("integer, parameter :: LONG_KIND=%d\n", sizeof(long));
    printf("integer, parameter :: SEEK_SET=%d\n", SEEK_SET);
    printf("integer, parameter :: SEEK_CUR=%d\n", SEEK_CUR);
    printf("integer, parameter :: SEEK_END=%d\n", SEEK_END);
    return 0;
}


