/*
  f90_unix_regexp_const.c : Determine values of constants for f90_unix_regexp

   This file is part of Posix90

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301, USA. 

 */

#include <stdio.h>
#include <sys/types.h>
#include <regex.h>

main(){

    printf("! DO NOT EDIT THIS FILE. \n");
    printf("! It is created from f90_unix_regexp_const.c\n");
    printf("integer, parameter :: REG_EXTENDED = %d\n", REG_EXTENDED);
    printf("integer, parameter :: REG_ICASE = %d\n", REG_ICASE);
    printf("integer, parameter :: REG_NOSUB = %d\n", REG_NOSUB);
    printf("integer, parameter :: REG_NEWLINE = %d\n", REG_NEWLINE);
    printf("integer, parameter :: REG_NOTBOL = %d\n", REG_NOTBOL);
    printf("integer, parameter :: REG_NOTEOL = %d\n", REG_NOTEOL);
    printf("integer, parameter :: REGEX_KIND = %d\n", sizeof(regex_t *));
    printf("integer, parameter :: REGMATCH_KIND = %d\n", sizeof(regmatch_t *));
    printf("integer, parameter :: REGOFF_KIND = %d\n", sizeof(regoff_t));
    return 0;
}


